### ISSUE TITLE
Check purchase again

### ISSUE THREAD

**Issue by giangmd** [ironkeith/moneris-eselectplus-api#6]
Hi,
The first I must enter number card for transaction and it ok.
For the next time, I not need enter the number card again for transaction. Can you sugguest?

**Comment by MarkyC** [comment]
@giangmd It sounds like you want to use the Vault API to tokenize a credit card. This turns a credit card PAN (e.g: 5454545454545454) into a token generated by Moneris. The token is mapped to that credit card, so be careful with it! But know that it can easily be invalidated, and/or re-created

I don't believe this library handles tokenization, though I would encourage you to add this functionality, and submit a pull request. This would help out @ironkeith and users of this library!

It also can be done using the official PHP API (`mpgClasses.php`) using the `res_add_cc` (add a new credit card, and tokenize) or `res_tokenize_cc` (tokenize a credit card that was used in a previous transaction) transaction types. To learn more, log into the [Moneris Developer Portal](https://developer.moneris.com) and click *Adding Vault Functionality* on the left nav. There should be a PDF and a zip of PHP examples.

**Comment by giangmd** [comment]
@MarkyC Thank you so much for your sugguest.
It is from Adding Vault Functionality in Moneris Document.

**Comment by MarkyC** [comment]
@giangmd you're welcome!

Feel free to close the ticket if you're satisfied with this approach.
